### ISSUE TITLE
Handle non-json (ie "raw") sources in `jq` macro

### ISSUE THREAD

**Issue by phlax** [aspect-build/bazel-lib#162]
`jq` itself will handle non json files in raw mode, but the macro doesnt

handling raw files would be particularly helpful when dealing with genquery output as `bazel query` doesnt support formatting results as json.

one workaround is to name the source files with a `.json` suffix but this means you have artefacts that are not valid json with json names

**Comment by kormide** [comment]
Released in https://github.com/aspect-build/bazel-lib/releases/tag/v1.3.1
