### ISSUE TITLE
Support for compiling jq if no binary available

### ISSUE THREAD

**Issue by phlax** [aspect-build/bazel-lib#174]
Seems upstream has no support for arm64 and a very slow dev/release cycle

Im wondering if the best workaround for this is to provide the ability to compile jq where there is no binary available

**Comment by kormide** [comment]
Are you working on an M1 processor? Doesn't the amd64 binary work with Rosetta?

**Comment by phlax** [comment]
no - its for https://github.com/envoyproxy/envoy ci/testing/build which runs on arm also

**Comment by kormide** [comment]
Given that the last jq release was three years ago, I doubt we'll be getting an arm64 binary any time soon. If you want to try the compilation approach and get a PR up I'd be happy to review.

Another option is for you to try our [yq](https://docs.aspect.build/aspect-build/bazel-lib/v1.0.0/docs/yq-docgen.html) rule, which, despite the name, can also parse and output json. They have an arm64 binary.

**Comment by kormide** [comment]
Going to close this for now as `yq` has an `arm64` binary and can do the same transformations as `jq`.
