### ISSUE TITLE
Consider failing by default when copy_to_directory encounters conflicting files

### ISSUE THREAD

**Issue by kormide** [aspect-build/bazel-lib#190]
Silently ignoring conflicts and not overwriting could be a source of tricky to find bugs. Both ignore and overwrite behaviours should be explicitly declared.

fyi @devversion

**Comment by gregmagolan** [comment]
Suppose we turn `allow_overwrites` into a `conflict_strategy` attribute with enum options `overwrite`, `ignore` and `fail` defaulting to `fail`.

**Comment by kormide** [comment]
Yeah I was thinking something along those lines as well.

**Comment by kormide** [comment]
Only downside is that there isn't an easy way to do this check with `cp`. We have to add some more complicated logic to search for potential conflicts first (I think).
