### ISSUE TITLE
Conflicting files in copy_file_action

### ISSUE THREAD

**Issue by purkhusid** [aspect-build/bazel-lib#220]
I'm using copy_file_action in a custom publishing rule and I've got an example of how it's used here:
https://github.com/purkhusid/rules_dotnet/blob/695ffff8b2dd4f4aae30372f0f3e094be52721dc/examples/publish_binary/BUILD#L21

The issue is that 2 targets try to create the exact same copy script on Windows because the inputs and outputs are the exact same files.

The culprit is this line here:
https://github.com/aspect-build/bazel-lib/blob/cd6c2f63ee380132fe8f206901de2abaa05ae385/lib/private/copy_file.bzl#L40

The comment above mentions that it's intentional to not have the label name in the file name but I'm not 100% understanding the reason for it. Would be be open up to a change that adds the label name to the bat file name?

**Comment by kormide** [comment]
This sounds familiar and may have been fixed in https://github.com/aspect-build/bazel-lib/commit/80603fb7eb92ba079762c182443b13d5dc9964f5. Do you want to try updating to the latest release, `1.10.1`?

**Comment by purkhusid** [comment]
@kormide I'm using the latest release. It seems like the fix fixes `copy_to_bin` but breaks `copy_file_action` in my case.
The change also doesn't make sense to me because by removing the label from the bat file name I would think that it would be more likely that the actions that create the bat output would collide.

**Comment by purkhusid** [comment]
Ah, the issue I have is that Bazel complains that there  are 2 different targets that output the same script file. So it's not the outputs of the copy action that conflict but the script files. I'll paste the error when I'm back at the computer.

**Comment by kormide** [comment]
> https://github.com/purkhusid/rules_dotnet/blob/695ffff8b2dd4f4aae30372f0f3e094be52721dc/examples/publish_binary/BUILD#L21

In the example you linked two, are those two targets supposed to produce two different output files with the same content, or the same output file?

If it's the former, maybe what I need to do here is name the script after a hash of the source and the destination file, rather than just the source.

**Comment by kormide** [comment]
I got a PR up that hopefully fixes your case: https://github.com/aspect-build/bazel-lib/pull/221

**Comment by purkhusid** [comment]
> > https://github.com/purkhusid/rules_dotnet/blob/695ffff8b2dd4f4aae30372f0f3e094be52721dc/examples/publish_binary/BUILD#L21
> 
> In the example you linked to, are those two targets supposed to produce two different output files with the same content, or the same output file?
> 
> If it's the former, maybe what I need to do here is name the script after a hash of the source and the destination file, rather than just the source.

Yes, that is the case. The error is:
```
ERROR: file 'publish_binary/478990217-cmd.bat' is generated by these conflicting actions:
Label: //publish_binary:publish_self_contained, //publish_binary:publish_not_self_contained
RuleClass: publish_binary_wrapper rule
Configuration: 2d025b54d1e798337c54da69c5ab51e6e250f93e5d6a812a4f1f0030d6869a75
Mnemonic: FileWrite
Action key: 596af37dc0561a5711b4554c15126ceef0006a085d8edc0916527b0584c6261d, 56060fef44722e1300d9738701c7d20e85b09abd07340c2b7d9f42b478638ea2
Progress message: Writing script publish_binary/478990217-cmd.bat
PrimaryInput: (null)
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-fastbuild/bin]publish_binary/478990217-cmd.bat
Owner information: ConfiguredTargetKey{label=//publish_binary:publish_self_contained, config=BuildConfigurationValue.Key[2d025b54d1e798337c54da69c5ab51e6e250f93e5d6a812a4f1f0030d6869a75]}, ConfiguredTargetKey{label=//publish_binary:publish_not_self_contained, config=BuildConfigurationValue.Key[2d025b54d1e798337c54da69c5ab51e6e250f93e5d6a812a4f1f0030d6869a75]}       
MandatoryInputs: are equal
Outputs: are equal
```
I'll test the fix when I get the time

**Comment by kormide** [comment]
@purkhusid I cut a release with the fix: https://github.com/aspect-build/bazel-lib/releases/tag/v1.11.0. Closing for now, but you can reopen if the problem persists.
