### ISSUE TITLE
Support stamping on yq rule

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/bazel-lib#223]
Useful for things like producing a package.json file that has the version field set from git tags.

**Comment by alexeagle** [comment]
Reopening to track the similar thing for yq (though I don't intend to do that now - the rules_js release story doesn't need it)

**Comment by malt3** [comment]
This would be great to support tag stamping in [rules_oci](https://github.com/bazel-contrib/rules_oci/blob/5ba2aceaac9c48fa1eca9090a0a9bd592e3d31cd/examples/push/stamp_tags.bzl#L29-L39) via yq.
The jq toolchain is not available on macOS with M1 or linux with arm64.

**Comment by opicaud** [comment]
Hi guys, 
Big thanks for this feature very vey useful!!

I've tried it and i have an issue that i replicate [here](https://github.com/opicaud/bazel-lib) with a red test when running
`bazel test --config=release //lib/tests/yq/...`
It's unfortunately not working when i stamp a value from stable-status.txt when I use the release config with bazel.
For info i am running on Bazel 5.4.0

**Comment by alexeagle** [comment]
Yup, I can repro that, looks like the yq expression

```
load_str(filename) | split("\n") | .[] 
    | select(length!=0)
    | [capture("(?P<key>[^\s]+)\s+(?P<value>.*)")]
```
only returns the first entry, which is why our tests for this passed.

**Comment by opicaud** [comment]
Working like a charm :) Thanks guys!
