### ISSUE TITLE
Allow symlinks for `copy_to_directory`

### ISSUE THREAD

**Issue by mnil** [aspect-build/bazel-lib#263]
Thanks for a very neat lib!

I was wondering if it would be possible to add an optional `allow_symlink = {True,False}` to `copy_to_directory` similar to how skylib have for `copy_file`:
https://github.com/bazelbuild/bazel-skylib/blob/main/tests/copy_file/BUILD#L123

**Comment by kormide** [comment]
I did a bit of investigation and I don't think this is possible at the moment.

`copy_to_directory` produces a TreeArtifact. Bazel doesn't seem to allow symlinks within TreeArtifacts. See https://bazel.build/rules/lib/actions#declare_symlink.

> Symlinks inside tree artifacts are not currently supported

I was able to get absolute symlinks working without Bazel complaining, but I think that would cause remote cache misses which is not ideal.

Feel free to reopen this if I'm missing something.
