### ISSUE TITLE
[Bug]: Incorrect diff_test failure with write_source_files to same folder

### ISSUE THREAD

**Issue by aran** [aspect-build/bazel-lib#291]
### What happened?

When using write_source_files with a generated file, writing to same folder, a `diff_test` clause introduced in https://github.com/aspect-build/bazel-lib/commit/b2955dcb052fea910192dfd9289751309c0bcaac fails with 

```
...external/aspect_bazel_lib/lib/private/diff_test.bzl", line 53, column 13, in _diff_test_impl
                fail(msg)
Error in fail: diff_test comparing the same file <generated file test/hello.txt>
```

I expect it the test to pass.

Here is the minimized repro:

`WORKSPACE`:
```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

####
# aspect_bazel_lib
####

http_archive(
    name = "aspect_bazel_lib",
    sha256 = "695d319362b227725e4daa60d863b4d1969b167889902511f1fd3051cea1071f",
    strip_prefix = "bazel-lib-1.16.3",
    url = "https://github.com/aspect-build/bazel-lib/archive/refs/tags/v1.16.3.tar.gz",
)

load("@aspect_bazel_lib//lib:repositories.bzl", "aspect_bazel_lib_dependencies")

aspect_bazel_lib_dependencies()
```

`test/BUILD`:
```starlark
load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")

FILE = "hello.txt"

genrule(
    name = "file",
    outs = [FILE],
    cmd = """cat << EOF > $@
Hello world.
EOF"""
)

write_source_files(
    name = "test",
    files = {
        FILE: ":file",
    },
)
```

### Version

Development (host) and target OS/architectures: macOS 12.6.1 (Intel)

Output of `bazel --version`: bazel 5.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: v1.16.3

Language(s) and/or frameworks involved: Just bash.

### How to reproduce

```shell
Given the above minimal repro, run the following: 


bazel run //test
bazel test //...
```
```


### Any other information?

_No response_

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
This issue is due to a limitation in the expressiveness of bazel targets.

Your write_source_files target:

```
write_source_files(
    name = "test",
    files = {
        "hello.txt": ":file",
    },
)
```

Fails because "hello.txt" is a pre-declared output of the `genrule` target. Give a label ":hello.txt" that could refer to a source (a file in the source tree) or an output file (a file in the output tree) of the same name, bazel will prefer the output file.

So the diff test is essentially comparing the output file to itself.

The way I generally get around this problem is to give the output file a different name from the source file:

```
genrule(
    name = "file",
    outs = ["_hello.txt"],
    cmd = """cat << EOF > $@
Hello world.
EOF"""
)

write_source_files(
    name = "test",
    files = {
        "hello.txt": ":_hello.txt",
    },
)
```

**Comment by aran** [comment]
Helpful explanation, thanks.
