### ISSUE TITLE
[Bug]: Regression in the `copy_to_directory` rule on Windows

### ISSUE THREAD

**Issue by pavi2410** [aspect-build/bazel-lib#328]
### What happened?

```
❯ bazel build //appinventor/appengine:MakeWar
INFO: Analyzed target //appinventor/appengine:MakeWar (1 packages loaded, 656 targets configured).
INFO: Found 1 target...
ERROR: D:/github/pavi2410/appinventor/appinventor/appengine/BUILD.bazel:179:18: Copying files to directory failed: (Exit 1): copy_to_directory.exe failed: error executing command (from target //appinventor/appengine:MakeWar) external\copy_to_directory_windows_amd64\copy_to_directory.exe bazel-out/x64_windows-fastbuild/bin/appinventor/appengine/MakeWar_config.json
2023/01/15 21:20:08 open bazel-out/x64_windows-fastbuild/bin/appinventor/appengine/MakeWar/extra/ode\soycReport\splitPoints21.xml.gz: The system cannot find the path specified.
Target //appinventor/appengine:MakeWar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.662s, Critical Path: 0.18s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

I'm using copy_to_directory rule to copy some build files to a different file under the bin directory. The path in the error above is the dest dir. Why does it attempt to open it? Where do I look for the problem?

### Version

Development (host) and target OS/architectures: Windows 11 64-bit

Output of `bazel --version`: bazel 6.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
- 1.19.2 working
- 1.20.0 not working
- 1.21.3 not working

Language(s) and/or frameworks involved:
Java, GWT, AppEngine

### How to reproduce

https://github.com/pavi2410/appinventor-sources/blob/0a96526fe572e7e50e6382dcb5ce2da7b55168d6/appinventor/appengine/BUILD.bazel#L184-L203

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Should be fixed in the next release by https://github.com/aspect-build/bazel-lib/commit/ce043b299df03f40e360cfe9ab37d89f3d552b56 and https://github.com/aspect-build/bazel-lib/commit/74caa5c09776303ea1d1ed7a9c74aecb6778127d.

**Comment by gregmagolan** [comment]
However, I'm not able to confirm this particular case is fixed since I'm hitting a JDK toolchain issue on my Windows machine before being able to build this particular target:
```
ERROR: C:/users/gmago/_bazel_greg/ilojnvke/external/local_jdk/BUILD.bazel:2:10: in fail_rule rule @local_jdk//:jdk:
Traceback (most recent call last):
        File "C:/users/gmago/_bazel_greg/ilojnvke/external/bazel_tools/tools/jdk/fail_rule.bzl", line 19, column 13, in _fail_rule_impl
                fail("%s %s" % (ctx.attr.header, ctx.attr.message))
Error in fail: Auto-Configuration Error: Cannot find Java binary bin/java.exe in C:/users/gmago/_bazel_greg/install/c9ea1a9caee100e72d651d25da00df4d/embedded_tools/tools/jdk/nosystemjdk; either correct your JAVA_HOME, PATH or specify Java from remote repository (e.g. --java_runtime_version=remotejdk_11
ERROR: C:/users/gmago/_bazel_greg/ilojnvke/external/local_jdk/BUILD.bazel:2:10: Analysis of target '@local_jdk//:jdk' failed
```

**Comment by gregmagolan** [comment]
@pavi2410 Could you please close this issue if the 1.23.3 release resolves this?

**Comment by pavi2410** [comment]
It's working fine again! Thanks for the quick fix!
