### ISSUE TITLE
[Bug]: Are there changes on the released artifacts?

### ISSUE THREAD

**Issue by chance-an** [aspect-build/bazel-lib#346]
### What happened?

We see that at least the following checksum is changed:

https://github.com/aspect-build/bazel-lib/archive/refs/tags/v1.10.0.tar.gz

➜  Downloads shasum -a 256 ./bazel-lib-1.10.0.tar.gz
5d3d968857e6e443cbbd3e97b97f46ab46b9a24853410b34538b8b683b648302  ./bazel-lib-1.10.0.tar.gz

The expected checksum is mentioned here:

https://github.com/aspect-build/bazel-lib/releases/tag/v1.10.0

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by parsnips** [comment]
I also encountered this on a different version of bazel-lib artifact starting today:

```
ERROR: no such package '@aspect_bazel_lib//lib': java.io.IOException: Error downloading [https://github.com/aspect-build/bazel-lib/archive/refs/tags/v1.18.0.tar.gz] to /mnt/data/root/.cache/bazel/_bazel_root/b7c0e49dc48477b0008fee9f624522db/external/aspect_bazel_lib/temp13692573677396786269/v1.18.0.tar.gz: Checksum was 8c64d4fc6f17d867255a7c0e6f771eae78223003a3545a7248afe11cd2ec07dd but wanted be236556c7b9c7b91cb370e837fdcec62b6e8893408cd4465ae883c9d7c67024
```

**Comment by tscurtu** [comment]
It's caused by this problematic Github deployment: https://news.ycombinator.com/item?id=34586917

Github said they would be reverting. I believe this issue can be closed.
