### ISSUE TITLE
write_source_files: quiet mode?

### ISSUE THREAD

**Issue by kjun9** [aspect-build/bazel-lib#412]
Hey there 👋 Thanks for maintaining this

For `write_source_files`, it would be nice if we could suppress these outputs: https://github.com/aspect-build/bazel-lib/blob/b983608c08cafd04fb20090c8df32a4bf282632f/lib/private/write_source_file.bzl#L211

WDYT? I'd be happy to have a go at a PR if that sounds reasonable

**Comment by kjun9** [comment]
Hey @alexeagle 👋 

What do you mean by:
> These only appear when manually accepting new files, right?

I'm using `write_source_files` to keep some generated code checked into my repo. The codegen generates 100+ files and  when I use `write_source_files` to copy them to sources, it's currently printing a line like this for _each_ of those files and I'm not sure how to turn them off:
```
Copying file <bazel-out-path> to <src-path> in <my-repo>
```
I want to turn them off because I want the ability to have more meaningful and concise logs than a wall of output like this.

**Comment by alexeagle** [comment]
We didn't hear back from you, so I assume it was resolved.
