### ISSUE TITLE
[FR]: Expose internal toolchains to end-users

### ISSUE THREAD

**Issue by nacl** [aspect-build/bazel-lib#415]
### What is the current behavior?

Toolchains like `jq_toolchain` are currently found in `lib/private`, which is intended for internal use only.

### Describe the feature

Modules in `private` directories are intended for internal use.  While downloading from Github is a reasonable default, there are cases where users may want to provide their own toolchains, such as:

- Unsupported architectures (e.g. https://github.com/aspect-build/bazel-lib/issues/268).
- Build hosts that are firewalled from the Internet.
- Build configurations that build jq or fetch it from a non-github source.

Currently, it is possible to create these toolchains easily enough by using things like this:

```starlark
load("@aspect_bazel_lib//lib/private:jq_toolchain.bzl", "jq_toolchain")
```

But this may eventually become inaccessible.  Please consider putting these in a public location so that end-users can create their own toolchains as needed.

---

An aside: it would also be nice if the toolchains could target arbitrary paths on the filesystem instead of labels, like what `rules_pkg` supports for its `rpmbuild` toolchain (https://github.com/bazelbuild/rules_pkg/blob/81da43d25ceb5cf51d75927f98d16799e2d94f47/toolchains/rpm/rpmbuild.bzl#L42-L58), but I can create a separate bug for that if y'all would like.

**Comment by alexeagle** [comment]
This sounds right to me. Incidentally, the lack of `jq` on some platform caused us to use `yq` instead in rules_oci, but that brought other unrelated issues when that tool had a big breaking change. So I'd love to make it easier to compile it from source too.

@kormide want to take this one?

**Comment by kormide** [comment]
For the time being we'd like to keep our public API surface small and not make `jq_toolchain` public. It's a fairly small rule and it's unlikely to change much, so for use cases like building a custom toolchain from source it's not too risky to rely on the private implementation. It's also easy to just copy and vendor it.

Re. the unsupported architectures: our 2.0 release (coming in October) features jq 1.7 which supports a larger variety of architectures.
