### ISSUE TITLE
[FR]: expand_template should support replacements, stamping

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/bazel-lib#431]
### What happened?

We depend on a private one here
https://github.com/aspect-build/rules_js/blob/main/js/private/expand_template.bzl#L115
in some Aspect projects and some of our clients, because it's such a useful utility.

It lives in rules_js because @gregmagolan needed to write a process to perform an action.

It ought to come from bazel-lib instead. Like copy_to_directory, we should port that JS program to a minimal Go program to perform the action, and distribute it as a pre-built toolchain.

Note, https://github.com/bazelbuild/bazel-skylib/issues/442 asks for the same thing on bazel-skylib

### Version

HEAD

**Comment by thesayyn** [comment]
fixed by #435
