### ISSUE TITLE
[Bug]: aspects_rules_js cannot load @aspect_bazel_lib//lib:base64.bzl

### ISSUE THREAD

**Issue by jungwookim** [aspect-build/bazel-lib#434]
### What happened?

`.../0a355af79acedc3d78422ddab00e3be6/external/aspect_rules_js/npm/private/npm_translate_lock_state.bzl:6:6: cannot load '@aspect_bazel_lib//lib:base64.bzl': no such file` when I follow up steps of migrating to rules_js.

I want to know why it can't find a file. It seems like no other loads.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 5.3.0 but I prefer use bazelisk

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: aspect_rules_js = 1.26.0, aspect_rules_ts=1.4.0

Language(s) and/or frameworks involved: javascript/typescript

### How to reproduce

```shell
I have the old WORKSPACE and I just added https://github.com/aspect-build/bazel-examples/blob/main/rules_nodejs_to_rules_js_migration/WORKSPACE#L1-L54 as a first step and but it occurs errors.
```

**Comment by gregmagolan** [comment]
This looks like a transitive deps issue in your WORKSPACE. You're likely pulling in and older version of aspect_bazel_lib that doesn't yet have the base64 utils that were added, https://github.com/aspect-build/bazel-lib/blob/main/lib/base64.bzl

**Comment by gregmagolan** [comment]
I also recommend Bazel 6 with rules_js as you'll get improved performance with optimizations rules_js is able to make with the latest versions of Bazel

**Comment by jungwookim** [comment]
I'm using the pretty old version of aspect_bazel_lib. This is resolved by updating the version to the latest and it works now.

I would consider following up the version of bazel 6 shortly as your advice. Thanks.
