### ISSUE TITLE
[Bug]: write_source_file runs code generation with diff_test = False and bazel test ...

### ISSUE THREAD

**Issue by monkeynova** [aspect-build/bazel-lib#497]
### What happened?

I've got a number of scripts that generates files that I want to be able to commit to my bazel reporistory. The write_source_file tool is great and a lot of the time, diff_test = True is what I want.

In one case, the script makes external RPCs in order to do it's job, and so I wanted that to not be part of my standard bazel test ... work, so I added diff_test = False to the target.

It turns out that this doesn't completely prevent my script from running on bazel test ...  calls, and I'm struggling to understand why and whether I'm missing something.

The script is not re-run on subsequent testing runs, so it's not the end of the world, but I'd really like to avoid making the calls when I haven't explicitly requested them.

### Version

Development (host) and target OS/architectures:  Mac OS
keith@keith-mbp:~/github/base-workspace $ uname -a
Darwin keith-mbp.localdomain 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64

Output of `bazel --version`:
keith@keith-mbp:~/github/base-workspace $ bazelisk --version
bazel 6.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
keith@keith-mbp:~/github/project-euler $ grep -B2 -A4 aspect WORKSPACE 

git_repository(
    name = "aspect_bazel_lib",
    remote = "https://github.com/aspect-build/bazel-lib.git",
    # branch = "main",
    commit = "e54912501619f34b7b2172a428ba0c4ebc2331af",
)

Language(s) and/or frameworks involved:
Codegen is a perl script. The repo is all C++

### How to reproduce

```shell
I can try to find a short reproduction if it helps, but I'm a bit far away from that right now and am making sure it's not something obvious from reading the bug report first.
```

**Comment by alexeagle** [comment]
I would guess the Bazel flag `--build_tests_only` is relevant here. The `diff_test` just compares two files in the output tree, there's likely a build step running prior to that which makes the network call.
