### ISSUE TITLE
[Bug]: Unabe to build on linux/arm64: JQ toolchain is not available

### ISSUE THREAD

**Issue by auzhva** [aspect-build/bazel-lib#502]
### What happened?

JQ toolchain is enabled only for linux/amd64 platform, no support for linux/arm64

### Version

linux/arm64
bazel 6.3.2

### Any other information?

See: https://github.com/aspect-build/bazel-lib/blob/main/lib/private/jq_toolchain.bzl#L6-L37

**Comment by mattem** [comment]
This seems like a duplicate of #268. Closing as the other has the relevant discussion. The alternative is currently to use `yq`, as suggested in https://github.com/aspect-build/bazel-lib/issues/174#issuecomment-1172741893
