### ISSUE TITLE
Document how to build your own libarchive-tools to get bsdtar

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/bazel-lib#577]
### What happened?

For the 2.0 release (on the `2.x` branch currently) we have a new `tar` toolchain.
It fetches bsdtar via the `libarchive-tools` package, by downloading `.deb` files from `ports.ubuntu.com` or `security.ubuntu.com`.

It's a bit brittle because:
- debian package registries are not immutable, once the 'focal' distro gets old enough, they'll remove these links
- we aren't principled about fetching the entire `.deb` dependency graph like `apt-get` would do
- it may not work with every linux distro where the ABI doesn't match what the libc these were compiled against, or where libc is very old
- don't support enough platforms (os/cpu combos)

Ideally the libarchive-tools package should probably appear on the Bazel Central Registry, so that BUILD files for it are community-maintained, and then it's pretty easy for us to document how a bazel-lib user could register that toolchain instead of our pre-built binaries.

### Version

2.0

**Comment by dzbarsky** [comment]
I can help on this one when I have more cycles, I already have something kinda-working for gzip/zstd, though it segfaults with xz compression :)

**Comment by alexeagle** [comment]
I think we can consider this done, now that https://registry.bazel.build/modules/libarchive shows how to build it from source, and users can register such a binary as the first toolchain to resolve.
