### ISSUE TITLE
[Bug]: bsd tar toolchain isn't totally hermetic

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/bazel-lib#615]
### What happened?

Currently we allow the glibc of the machine to be used, so we don't work on Ubuntu 18 for example.

And on Windows we rely on some DLLs so you might get `Exit -1073741515`
which is an integer conversion of `0xC0000135 STATUS_DLL_NOT_FOUND`

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55?redirectedfrom=MSDN

### Version

2.0.0-rc0

**Comment by dzbarsky** [comment]
Yep in https://github.com/dzbarsky/libarchive/blob/master/BUILD.bazel#L40-L61 I link aginst musl to avoid the glibc issue. not sure about Windows, don't have a way to test. Happy to collab on this to provide prebuilt binaries if you're interested

**Comment by alexeagle** [comment]
Sahin found that Nix cache also supplies musl-linked libarchive binaries. Either is fine! I'm just a stickler about this repo not containing any code to build them because I don't want to own it. But you could put libarchive on the BCR!

**Comment by alexeagle** [comment]
@dzbarsky I just got hit by this again at a client. Let's try to get libarchive/libarchive onto the BCR?

**Comment by DavidZbarsky-at** [comment]
Sounds good. Xz is already there so we probably just need zstd and libarchive to get food coverage. Is the BCR CLl the best way to add an overlay to an existing repo?

**Comment by Strum355** [comment]
Just to add to this, Im also facing this (admittedly Im on NixOS)
```
INFO: Analyzed target //cmd/batcheshelper:image_tarball (353 packages loaded, 17402 targets configured).
ERROR: /home/noah/Sourcegraph/sourcegraph/cmd/batcheshelper/BUILD.bazel:57:12: OCI Tarball //cmd/batcheshelper:image_tarball failed: (Exit 127): tarball.sh failed: error executing OCITarball command (from target //cmd/batcheshelper:image_tarball) bazel-out/k8-fastbuild/bin/cmd/batcheshelper/image_tarball/tarball.sh

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/bsd_tar_linux_amd64/usr/bin/bsdtar: error while loading shared libraries: libacl.so.1: cannot open shared object file: No such file or directory
```

There is also another report from Dec 2023 (for a different shared library) https://github.com/aspect-build/bazel-lib/issues/698

**Comment by alexeagle** [comment]
Thanks @DavidZbarsky-at for the fix! We now get tar from https://github.com/aspect-build/bsdtar-prebuilt based on the libarchive entry in BCR.
