### ISSUE TITLE
[Bug]: tar non-hermeticity due to different sandboxing strategies.

### ISSUE THREAD

**Issue by thesayyn** [aspect-build/bazel-lib#620]
### What happened?

bsdtar has a non-hermetic behavior across local sandboxing strategies and RBE implementations. 

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

### How to reproduce

```shell
https://github.com/aspect-build/bazel-lib/pull/609
```

**Comment by alexeagle** [comment]
This should no longer be a problem since we use a statically-linked binary from https://registry.bazel.build/modules/libarchive
