### ISSUE TITLE
[Bug]: tar linux toolchain has no hermetic glibc

### ISSUE THREAD

**Issue by thesayyn** [aspect-build/bazel-lib#621]
### What happened?

bsdtar linux toolchain doesn't fetch glibc, instead relies on a really specific version of glibc which might not work on some distros.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

**Comment by alexeagle** [comment]
dupe of #615
