### ISSUE TITLE
[Bug]: tar mtree should expand treeartifacts automatically

### ISSUE THREAD

**Issue by thesayyn** [aspect-build/bazel-lib#625]
### What happened?

Currently, only treeartifacts root directory is added as directory without the contents. bsdtar doesn't automatically expand directories, this should be done beforehand.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:

**Comment by thesayyn** [comment]
It will fail horribly with following error;

```
Error reading archive bazel-out/darwin_arm64-opt/bin/lib/tests/tar/_transform.mtree.txt: mtree specification has different type for package/pkg
```

**Comment by mvgijssel** [comment]
Running into issue in https://github.com/vgijssel/setup/pull/544, where I'm trying to package up a py_binary with deps coming from https://github.com/jvolkman/rules_pycross. That rule set outputs a package as a single directory (instead as separate file) as can be seen here https://github.com/jvolkman/rules_pycross/blob/c6923332dacb3ef5c4df172155be526981a140ab/pycross/private/wheel_library.bzl#L8. 

The error I'm getting:

```
ERROR: /Users/maarten/Development/setup/tools/bunq2ynab/BUILD.bazel:116:9: Tar tools/bunq2ynab/bunq2ynab_image_python_layer.tar failed: (Exit 1): tar failed: error executing command (from target //tools/bunq2ynab:bunq2ynab_image_python_layer) external/aspect_bazel_lib~2.0.0-rc0~toolchains~bsd_tar_host/tar --create --file bazel-out/darwin_arm64-fastbuild-ST-59894ec379d6/bin/tools/bunq2ynab/bunq2ynab_image_python_layer.tar ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
tar: Error reading archive bazel-out/darwin_arm64-fastbuild-ST-59894ec379d6/bin/tools/bunq2ynab/bunq2ynab_image_python_layer_mtree_prefixed.txt: mtree specification has different type for opt/tools/bunq2ynab/bunq2ynab.runfiles/pdm-setup/deps/requests_2.31.0
tar: Error exit delayed from previous errors.
Target //tools/bunq2ynab:bunq2ynab_image_run failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by mvgijssel** [comment]
I think this is actually fixed by https://github.com/aspect-build/bazel-lib/pull/630! Using `bazel_dep(name = "aspect_bazel_lib", version = "2.0.0-rc1")` solves it for me 🎉

**Comment by thesayyn** [comment]
fixed by https://github.com/aspect-build/bazel-lib/pull/630
