### ISSUE TITLE
[Bug]: stamping volatile-status with jq uses stale values

### ISSUE THREAD

**Issue by leungster** [aspect-build/bazel-lib#636]
### What happened?

When stamping with `jq`, the volatile status values are stale on subsequent executions of the `jq` rule. Changing the input `src` and `filter` has no effect on refreshing the volatile status values. 

While debugging, it appears that the `_<name>_stamp.json` file that maps the stable/volatile status entries into json is being cached. Since my stable values aren't changing, the `run_shell` action is returning a stale output.

### Version

Development (host) and target OS/architectures:
`Darwin/amd64`

Output of `bazel --version`:
`bazel 6.4.0`

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
`bazel-lib 1.32.1`

### How to reproduce

```shell
Executing this target the first time with an arbitrary `version` uses the latest timestamp in `volatile-status.txt`. 
Subsequent calls to the target with different `version` uses the stale timestamp value even though `volatile-status.txt` has been updated and `version` is updated.


    jq(
        name = "package",
        srcs = ["package.json"],
        filter = "|".join([
            "$ARGS.named.STAMP as $stamp",
            '.timestamp = ($stamp.{} // "unstamped")'.format("BUILD_TIMESTAMP"),
            '.version = "{}"'.format(version),
        ],
        **kwargs
    )
```
```


### Any other information?

Current workaround is to do a `bazel clean` prior to stamping. Alternatively if the volatile-status field is "stable" then convert it to a stable status.

**Comment by kormide** [comment]
It seems this is because `filter` and `srcs` aren't inputs to the action that creates the file with stamped vars. We could add `srcs` to the inputs of that action, and I suppose we could write a string filter to a file then also pass that in. Does that sound right, @alexeagle ?

**Comment by alexeagle** [comment]
It feels pretty obscure to me that you'd use a volatile status, which is always subject to being stale due to caching, and then care about exactly which actions are produced by the jq implementation.
It's true that we can simply pass the srcs to bust that action from the cache all the time, but it feels like making everyone's build slower for an obscure use case.
I'd rather not add complexity to the jq rule, but rather suggest a workaround like `--action_env=CACHE=bust` or just use a different rule like `expand_template` that doesn't have this problem.

**Comment by leungster** [comment]
I think it's an unexpected behavior given that the inputs to `jq` changed. Perhaps it's a documentation improvement.

I have a workaround to additionally stamp a stable status and this is no longer an issue for our use case.

**Comment by alexeagle** [comment]
Yeah I understand why it's unexpected. But it's pretty common for Bazel rules to produce several actions, and not all actions take all the declared `srcs` as inputs, so it's never safe to assume that volatile status keys will get picked up by one of them.

I agree with using a stable status for this use case.
