### ISSUE TITLE
[Bug]: write_source_files does not copy hidden files

### ISSUE THREAD

**Issue by kormide** [aspect-build/bazel-lib#667]
### What happened?

Files that begin with a `.` are not copied, regardless of whether the source is in the source tree or the output tree.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: 6.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved: 2.0.1

### How to reproduce

```shell
Include a hidden file in a write_source_files targets. Observe that it does not get written.
```

### Any other information?

I have a patch in this PR to fix it: https://github.com/aspect-build/rules_js/pull/1366

However, it does not copy executable bits. That may be a separate issue related to https://github.com/aspect-build/bazel-lib/issues/526, however.

**Comment by jgiles** [comment]
@kormide I think https://github.com/aspect-build/bazel-lib/pull/860 should resolve.
