### ISSUE TITLE
[Bug]: release path has a "v" in the tag where the tar prefix doesn't

### ISSUE THREAD

**Issue by matt-sm** [aspect-build/bazel-lib#678]
### What happened?

In a release example:

```
http_archive(
    name = "aspect_bazel_lib",
    sha256 = "4d6010ca5e3bb4d7045b071205afa8db06ec11eb24de3f023d74d77cca765f66",
    strip_prefix = "bazel-lib-1.39.0",
    url = "https://github.com/aspect-build/bazel-lib/releases/download/v1.39.0/bazel-lib-v1.39.0.tar.gz",
)
```
the url has a `v` in the path where the strip prefix doesn't

this makes it hard to create abstractions over http_archive

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: N/A

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 1.39.0

Language(s) and/or frameworks involved: N/A

**Comment by alexeagle** [comment]
This is very intentional, it matches what GitHub serves if you point to an archive of the repository that it serves. We want the http_archive call to be easily switched between release artifacts and github source archives.

**Comment by alexeagle** [comment]
BTW here's the source-of-truth for where the `v` got stripped: https://github.com/bazel-contrib/rules-template/blob/main/.github/workflows/release_prep.sh#L8-L12
(it's shared by dozens of bazel rulesets)

**Comment by matt-sm** [comment]
Thanks for the info @alexeagle
