### ISSUE TITLE
[Bug]: coreutils toolchain depends on glibc

### ISSUE THREAD

**Issue by malt3** [aspect-build/bazel-lib#701]
### What happened?

Similar to the issues with bsdtar, the coreutils toolchain currently used (from uutils) is linking against glibc on Linux.
This fails on some platforms (including NixOS) and is not actually hermetic.
Uutils has a statically linked variant of coreutils available as an alternative release artifact. Could `bazel-lib` use this (either by default or as a configurable option)?

Happy to provide a fix as a PR.

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`:

6.4.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
aspect bazel-lib 2.0.3
rules_oci 1.5.1

Language(s) and/or frameworks involved: n/a

### How to reproduce

```shell
Use the `oci_image` rule from rules_oci on a NixOS or alpine Linux host.
The rules has a new output (_index_json_cp), which fails to build:

-session
❯ bazel build //e2e/malicious-join:_malicious-join_image_index_json_cp
INFO: Analyzed target //e2e/malicious-join:_malicious-join_image_index_json_cp (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/malte/github.com/edgelesssys/constellation/e2e/malicious-join/BUILD.bazel:41:10: Copying file e2e/malicious-join/malicious-join_image failed: (Exit 1): coreutils failed: error executing command (from target //e2e/malicious-join:_malicious-join_image_index_json_cp) external/coreutils_linux_amd64/coreutils cp bazel-out/k8-opt/bin/e2e/malicious-join/malicious-join_image/index.json bazel-out/k8-opt/bin/e2e/malicious-join/_malicious-join_image_index.json
src/main/tools/process-wrapper-legacy.cc:80: "execvp(external/coreutils_linux_amd64/coreutils, ...)": No such file or directory
Target //e2e/malicious-join:_malicious-join_image_index_json_cp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.394s, Critical Path: 0.05s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by alexeagle** [comment]
> Uutils has a statically linked variant of coreutils available as an alternative release artifact. Could bazel-lib use this 

That sounds great! We'd rather have a larger download and get a statically-linked binary.

**Comment by malt3** [comment]
Gentle ping: could you review either #706 or #720?
