### ISSUE TITLE
[FR]: Add option to `copy_to_directory` to flatten the output tree structure

### ISSUE THREAD

**Issue by aaronsky** [aspect-build/bazel-lib#756]
### What is the current behavior?

Directories input to this rule are copied while retaining the previous tree structure, which is opaque to Bazel.

### Describe the feature

It would be useful for me to add a `flatten` field to the rule, as input to the `copy_to_directory` binary. This option would produce the flattened representation of the input directory tree as output, resulting in a set of files with no internal nesting.

**Comment by kormide** [comment]
@aaronsky You can accomplish a flatten operation by doing:

```
copy_to_directory(
    name = "flattened",
    srcs = ["some_dir"],
    root_paths = ["%s/some_dir/**" % package_name()],
)
```

I'll close the issue assuming this addresses your use case, but if not then feel free to re-open.
