### ISSUE TITLE
[FR]: Propagate Tags to Tar

### ISSUE THREAD

**Issue by Ryang20718** [aspect-build/bazel-lib#776]
### What is the current behavior?

if we have tags such as `no-remote-cache` and a bazel remote cache, when using tar to create python docker images (giant images), we want to avoid pushing to the cache. 

### Describe the feature

We'd like to propagate tags to Tar so we avoid the remote cache

i.e
https://github.com/aspect-build/bazel-lib/blob/4f684081d752eb618c36d6627896738577c6effa/lib/private/tar.bzl#L151-L159

Happy to make a PR request, but wanted to ask if this would be acceptable first!

**Comment by alexeagle** [comment]
The tags should already propagate correctly. They are passed through here https://github.com/aspect-build/bazel-lib/blob/main/lib/tar.bzl#L131

Perhaps you're missing https://github.com/bazelbuild/bazel/issues/8830 ?
