### ISSUE TITLE
[Bug]: bsdtar toolchain fails on macOS if host tar is gnutar

### ISSUE THREAD

**Issue by Strum355** [aspect-build/bazel-lib#788]
### What happened?

bazel-lib doesnt provide any non-host bsdtar toolchains on macOS. This causes a hard-fail when the host tar binary is a gnutar implementation instead of bsdtar, as is the case when e.g. running inside a Nix shell. 
It may be expected that in this case, one should provide their own bsdtar toolchain, in which case this is working-as-intended. It would definitely be more convenient though for bazel-lib to also provide that : )

### Version

Development (host) and target OS/architectures: macOS arm64

Output of `bazel --version`: aspect 5.8.19

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 2.5.3

Language(s) and/or frameworks involved: Nix

**Comment by pcj** [comment]
Also seeing this

**Comment by alexeagle** [comment]
We'll use https://github.com/dzbarsky/bsdtar/releases/tag/v3.7.2 which includes darwin binaries to fix this.
