### ISSUE TITLE
[Bug]: unable to use expand_template in v2

### ISSUE THREAD

**Issue by jschaf** [aspect-build/bazel-lib#802]
### What happened?

I upgraded the Aspect bazel-lib from v1 to v2 and was unable to use expand_template because no matching toolchain was found.

### Version

Development (host) and target OS/architectures: Host platform is macOS/arm64

Output of `bazel --version`: bazel 6.3.2

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: 2.5.3

Language(s) and/or frameworks involved: none.

### How to reproduce

Run `bazel --bazelrc=/dev/null build :foo`

Results in the following error:

While resolving toolchains for target //build/container:foo:

```
No matching toolchains found for types @aspect_bazel_lib//lib:expand_template_toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@aspect_bazel_lib//lib:expand_template_toolchain_type'
```

### BUILD.bazel
```
load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")

expand_template(
    name = "foo",
    out = "foo.txt",
    substitutions = {
        "{{FOO}}": "{{FOO}}",
    },
    template = ":foo.txt.tmpl",
    tags = ["manual"],
)
```

### foo.txt.tmpl
```
{{FOO}}
```

### Any other information?

v2.5.3: fails (latest)
v2.1.2: fails
v2.0.0: fails

v1.42.1: succeeds (latest)
v1.38.0: succeeds

**Comment by alexeagle** [comment]
See the release notes, you have to register the toolchain yourself starting in v2.
e.g. `aspect_bazel_lib_register_toolchains()`
