### ISSUE TITLE
[FR]: tar is non-hermetic when compress is set to zstd

### ISSUE THREAD

**Issue by ewhauser** [aspect-build/bazel-lib#877]
### What is the current behavior?

When `tar` is configured using `compress = "zstd"`, it looks for `zstd` on the path. If the `zstd_toolchain` is registered, then we should append this to path.

### Describe the feature

We want to make `tar` hermetic when using `zstd` compression.

**Comment by alexeagle** [comment]
The bug is actually in the BCR entry for libarchive, see https://github.com/aspect-build/bazel-lib/pull/878#issuecomment-2225981766

**Comment by mattem** [comment]
[Related to a Slack conversation](https://aspect.unthread.io/dashboard/inbox/all/conversations/2ac6b7f8-dbad-4346-a55a-d90afe6c0a15)
